import React, { useState } from "react";
import axios from "axios";
import "./Recommendations.css";
import { useNavigate } from "react-router-dom";

function Recommendations() {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const navigate = useNavigate();
  const [selectedJob, setSelectedJob] = useState(null); // ✅ for showing job details

  const fetchRecommendations = async () => {
    setLoading(true);
    setErrorMsg("");
    try {
      const res = await axios.get("http://localhost:5000/api/recommendations", {
        withCredentials: true,
      });
      if (res.data.recommendations && res.data.recommendations.length > 0) {
        setRecommendations(res.data.recommendations);
      } else {
        setRecommendations([]);
        setErrorMsg("No recommendations found yet. Click the button again later.");
      }
    } catch (err) {
      console.error("Error fetching recommendations:", err);
      setErrorMsg("Error fetching recommendations. Make sure you are logged in.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="recommendations-container">
      <h1>AI-Powered Job Recommendations</h1>
      <p className="subtitle">
        These recommendations are generated by combining your resume data with 
        behavioral insights to ensure the best career matches for you.
      </p>

      <button
        className="primary-btn"
        onClick={fetchRecommendations}
        disabled={loading}
      >
        {loading ? "Fetching..." : "Get Recommendation"}
      </button>

      <div className="recommendations-list">
        {recommendations.length > 0 ? (
          recommendations.map((job, index) => (
            <div
              key={index}
              className="job-card"
              onClick={() => setSelectedJob(job)} // ✅ click to show details
            >
              <h3>{job.job_role}</h3>
              <p>
                <strong>Company:</strong> {job.company_name} ({job.company_type})
              </p>
              <p>
                <strong>Match Score:</strong> {job.similarity_score.toFixed(2)}
              </p>
            </div>
          ))
        ) : (
          !loading && <p className="no-data">{errorMsg || "No recommendations yet. Click the button above."}</p>
        )}
      </div>

      {/* Job Details Modal */}
      {selectedJob && (
  <div className="job-modal" onClick={() => setSelectedJob(null)}>
    <div className="job-modal-content" onClick={(e) => e.stopPropagation()}>
      <h2>{selectedJob.job_role}</h2>
      <p><strong>Company:</strong> {selectedJob.company_name} ({selectedJob.company_type})</p>
      <p><strong>Match Score:</strong> {selectedJob.similarity_score.toFixed(2)}%</p>
      <p><strong>Knowledge Required:</strong> {selectedJob.knowledge || "Not provided"}</p>
      <p><strong>Skills Required:</strong> {selectedJob.skills || "Not provided"}</p>
      <button className="close-btn" onClick={() => setSelectedJob(null)}>Close</button>
    </div>
  </div>
)}
<button className="secondary-btn" onClick={() => navigate("/home")}>
          Back to Home
        </button>
    </div>
  );
}

export default Recommendations;
